"""change intake_year data type

Revision ID: 0873ead2e74c
Revises: 6b700d6cca62
Create Date: 2024-11-23 16:19:45.976779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0873ead2e74c'
down_revision = '6b700d6cca62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.alter_column('intake_year',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('intake',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.alter_column('intake',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('intake_year',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
