"""add column status at exchange table

Revision ID: 16ca003082b5
Revises: 6c0477a33b67
Create Date: 2024-11-19 22:58:52.472042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ca003082b5'
down_revision = '6c0477a33b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bpp', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.alter_column('student_folder',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('intake',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('from_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('until',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('student_detail',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('jenis_exchange',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.alter_column('jenis_exchange',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('student_detail',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('until',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('from_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('intake',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('student_folder',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('location')

    with op.batch_alter_table('bpp', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('period',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
