"""menambah kolom untuk input file

Revision ID: 3f45ec5fc40d
Revises: cef89cb46612
Create Date: 2024-12-21 23:15:59.013485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45ec5fc40d'
down_revision = 'cef89cb46612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letter_of_Acc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.drop_column('letter_of_Acc')

    # ### end Alembic commands ###
