"""menambah kolom untuk input file tambahan

Revision ID: 434c96562974
Revises: 3f45ec5fc40d
Create Date: 2024-12-21 23:35:44.602529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434c96562974'
down_revision = '3f45ec5fc40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('others_docs', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.drop_column('others_docs')

    # ### end Alembic commands ###
