"""add bpp table

Revision ID: 6c0477a33b67
Revises: 
Create Date: 2024-11-19 16:38:04.011972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0477a33b67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa',
    sa.Column('nim', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('wali', sa.String(), nullable=False),
    sa.Column('angkatan', sa.Integer(), nullable=False),
    sa.Column('kode_angkatan', sa.String(), nullable=False),
    sa.Column('tanggal_masuk', sa.Date(), nullable=False),
    sa.Column('tanggal_keluar', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('student_folder', sa.String(), nullable=False),
    sa.Column('esyp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nim'], ['users.id'], ),
    sa.PrimaryKeyConstraint('nim')
    )
    op.create_table('bpp',
    sa.Column('nim', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ),
    sa.PrimaryKeyConstraint('nim')
    )
    op.create_table('exchange_outbound',
    sa.Column('nim', sa.Integer(), nullable=False),
    sa.Column('student_folder', sa.Integer(), nullable=False),
    sa.Column('intake', sa.Date(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('until', sa.Date(), nullable=False),
    sa.Column('student_detail', sa.String(), nullable=False),
    sa.Column('jenis_exchange', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ),
    sa.PrimaryKeyConstraint('nim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_outbound')
    op.drop_table('bpp')
    op.drop_table('mahasiswa')
    op.drop_table('users')
    # ### end Alembic commands ###
