"""add new column

Revision ID: c15a9c01d3d1
Revises: 16ca003082b5
Create Date: 2024-11-19 23:16:11.173917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15a9c01d3d1'
down_revision = '16ca003082b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_at_telu', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('intake_year', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.drop_column('intake_year')
        batch_op.drop_column('semester_at_telu')

    # ### end Alembic commands ###
