"""add univ target

Revision ID: cef89cb46612
Revises: 0873ead2e74c
Create Date: 2024-11-27 13:06:32.812850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef89cb46612'
down_revision = '0873ead2e74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('univ', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_outbound', schema=None) as batch_op:
        batch_op.drop_column('univ')

    # ### end Alembic commands ###
