"""Initial migration

Revision ID: d55265c42672
Revises: 
Create Date: 2024-12-24 13:45:27.560322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55265c42672'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa',
    sa.Column('nim', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('wali', sa.String(), nullable=False),
    sa.Column('angkatan', sa.Integer(), nullable=False),
    sa.Column('kode_angkatan', sa.String(), nullable=False),
    sa.Column('tanggal_masuk', sa.Date(), nullable=False),
    sa.Column('tanggal_keluar', sa.Date(), nullable=False),
    sa.Column('gpa', sa.String(), nullable=False),
    sa.Column('esyp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nim'], ['users.id'], ),
    sa.PrimaryKeyConstraint('nim')
    )
    op.create_table('bpp',
    sa.Column('nim', sa.Integer(), nullable=True),
    sa.Column('id_program', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ),
    sa.PrimaryKeyConstraint('id_program')
    )
    op.create_table('exchange_outbound',
    sa.Column('id_', sa.String(), nullable=False),
    sa.Column('nim', sa.Integer(), nullable=True),
    sa.Column('student_folder', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('univ', sa.String(), nullable=True),
    sa.Column('intake_year', sa.String(), nullable=True),
    sa.Column('intake', sa.Date(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('until', sa.Date(), nullable=True),
    sa.Column('letter_of_Acc', sa.String(), nullable=True),
    sa.Column('sem_at_telu', sa.String(), nullable=True),
    sa.Column('sem_at_exch', sa.String(), nullable=True),
    sa.Column('gpa', sa.String(), nullable=True),
    sa.Column('update_gpa', sa.Date(), nullable=True),
    sa.Column('transcript_telu', sa.String(), nullable=True),
    sa.Column('transcript_exch', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('jenis_exchange', sa.String(), nullable=True),
    sa.Column('student_detail', sa.String(), nullable=True),
    sa.Column('others_docs', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], name='fk_exchange_outbound_nim'),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_outbound')
    op.drop_table('bpp')
    op.drop_table('mahasiswa')
    op.drop_table('users')
    # ### end Alembic commands ###
